### ISSUE TITLE
Problem: nothing provides 'libuuid' on OpenSUSE Tumbleweed

### ISSUE THREAD

**Issue by jw-chrisg** [inspectdev/inspect-issues#100]
This is the error message when installing the app, although I have the following in my machine:
- libuuid-devel
- libuuid1

**Comment by auchenberg** [comment]
This seems to be related to Electron. https://github.com/Automattic/simplenote-electron/issues/2038

**Comment by cgxwebs** [comment]
Installation works if you ignore the dependency message, libuuid1 works it just comes with a different name.  I guess this can be closed. Thank you.

**Comment by cgxwebs** [comment]
Installation works if you ignore the dependency message, libuuid1 works it just comes with a different name. I guess this can be closed. Thank you.

**Comment by jw-chrisg** [comment]
Installation works if you ignore the dependency message, libuuid1 works it just comes with a different name. I guess this can be closed. Thank you.
