### ISSUE TITLE
iOS 15 + Windows: Inspect doesn't detect my devices or doesn't work

### ISSUE THREAD

**Issue by auchenberg** [inspectdev/inspect-issues#101]
From customer:

I'm trying to use inspect on windows 11 to inspect my iphone 11 (Running ios 15.0.2), however inspect is unreliable. Sometimes my phone doesn't show up, sometimes it doesn't show any websites open in safari and almost all of the time when clicking on a site when it finally appears, results in a blank screen (See image). When restarting inspect multiple times to get it working, a page reload on my phone or one wrong click in inspect is enough to freeze inspect completely.
![unnamed](https://user-images.githubusercontent.com/173559/140676976-a26c7af3-a3c8-4370-8371-ad9e64bc54e9.png)

**Comment by spreadpando** [comment]
I have the same issue on iOS 14.8.1

**Comment by auchenberg** [comment]
@spreadpando @nhwilly Can I get you to try to use the latest version of Inspect, and let me know how it works? What kind of target are you trying to debug?

**Comment by nhwilly** [comment]
@auchenberg I am neck deep in the back end of a project at the moment and won't be able to get to this in a timely fashion.  If I can catch a break, I'll try.

**Comment by auchenberg** [comment]
@nhwilly No rush, whenever you have time. I appricate the feedback!

**Comment by spreadpando** [comment]
Likewise fairly busy with client work at the moment. I may find time this weekend. I'm debugging single page webXR applications from windows 10 / iPhone 7.

**Comment by auchenberg** [comment]
Closing as I assume it has been fixed.
