### ISSUE TITLE
Cookies: Unable to clear cookie on Safari iOS 15.1

### ISSUE THREAD

**Issue by SuperPat45** [inspectdev/inspect-issues#103]
- Inspect version: 0.7.5
- Electron: 15.3.1
- OS version and architecture: win32 x64 10.0.19044
- Language: undefined

Steps to Reproduce:

1. Open a page on safari
2. Inspect this page
3. Go to Application / Cookies
4. Try deleting a single cookie or clear all cookies
5. Cookie still present…

**Comment by auchenberg** [comment]
Good catch @SuperPat45! This will be fixed in next release
