### ISSUE TITLE
Console: The console preserve log through navigation even when the checkbox is unchecked

### ISSUE THREAD

**Issue by SuperPat45** [inspectdev/inspect-issues#104]
- Inspect version: 0.7.5
- Electron: 15.3.1
- OS version and architecture: win32 x64 10.0.19044
- Language: undefined

Steps to Reproduce:

1. Open a page with Safari on ios 15
2. In the console log, uncheck the "Preserve log" option
3. Reload page or navigate to another one
4. The log is not cleared between pages

**Comment by auchenberg** [comment]
Good catch @SuperPat45! This will also land in the next release
