### ISSUE TITLE
Inspect does not identify my Safari

### ISSUE THREAD

**Issue by jonasmarco** [inspectdev/inspect-issues#105]
- Inspect version: 0.7.5
- Electron: 15.3.1
- OS version and architecture: win32 x64 10.0.22000
- Language: undefined
- iOS 15.1.1
- Windows 11

I did the entire procedure.
I downloaded iTunes, plugged in my iPhone, released inspector mode in Safari. My iPhone appears in Inspect. But when I open Safari nothing happens.

**Comment by auchenberg** [comment]
Hi,

Have you tried to follow the Windows specific instructions in https://help.inspect.dev/en/articles/5601931-inspect-can-t-find-my-safari-tabs?

**Comment by auchenberg** [comment]
Marking as duplicate of https://github.com/inspectdev/inspect-issues/issues/101

**Comment by auchenberg** [comment]
@jonasmarco Can I get you to try to use the latest version of Inspect, and let me know how it works? What kind of target are you trying to debug?

**Comment by jonasmarco** [comment]
@auchenberg 

sorry for the delay, i will test this week and came back with a feedback
