### ISSUE TITLE
Improve Windows getting started experience

### ISSUE THREAD

**Issue by auchenberg** [inspectdev/inspect-issues#11]
Given Windows requires iTunes to be installed, Inspect should detect this automatically and show instructions on how to get going .

- "Hello, sorry for late answer. I got the solution by opening iTunes on Windows. I understood that by having iTunes installed was enough but I had to open it to see the targets. Thanks for the answer."

- "I was having the same issue, auchenbeg's comment about Enabling Web Inspector worked for me! Can someone on the inspect team add that step to the Download page? https://inspect.dev/download That would be super helpful."

**Comment by FrancescRRSapa** [comment]
I had to manually open Itunes for inspect to find my device, I thought having it installed was enough.

**Comment by auchenberg** [comment]
Add note to start iTunes on WIndows
