### ISSUE TITLE
DevTools: Disable screencast view by default

### ISSUE THREAD

**Issue by auchenberg** [inspectdev/inspect-issues#113]
Disable screencast view by default, so it doesn't open up to users the first time they use it.

**Comment by mirko77** [comment]
@auchenberg And the solution is? I still get it open all the times on Chrome Version 122.0.6261.94 (Official Build) (arm64)

**Comment by auchenberg** [comment]
@mirko77 If you close the screencasting view the first time, Inspect should remember this when you open the DevTools the next time.
