### ISSUE TITLE
Code area is not refreshed, version 0.7.7

### ISSUE THREAD

**Issue by zxerqw** [inspectdev/inspect-issues#118]
It was working fine before 0.7.7, when I placed a breakpoint I needed to refresh the page to make it work(ctrl+r), but it only refreshed the page on the phone, not the code area at the same time
![image](https://user-images.githubusercontent.com/16666177/148872700-cedf232d-286f-498d-96df-818a38575510.png)

**Comment by auchenberg** [comment]
@zxerqw Not sure I understand. Is the problem that the loaded scripts don't show up under Sources anymore? What device, iOS version and target are you trying to debug? Does the Console and Elements work?

**Comment by zxerqw** [comment]
No, the script displays properly the first time, but when I use ctrl+r to refresh it, it doesn't refresh, but the phone's interface does, and it used to be able to refresh both.

**Comment by auchenberg** [comment]
@zxerqw Very interesting. Would it be possible for you to outline the specific steps on how to reproduce? I can't here.

**Comment by zxerqw** [comment]
version 0.7.6 with safari works fine
![Animation](https://user-images.githubusercontent.com/16666177/148891467-cbe5e4a4-d2a0-431e-a176-d995e0663e35.gif)
version 0.7.7 with third party app:
![11](https://user-images.githubusercontent.com/16666177/148892756-42541657-774b-41d8-b6ef-6456f9486234.gif)

The problem is like Gif 2, once I refresh, the code area disappears or gets stcuk(no such problem below version 7.7), I need to select the page again, I think this problem is in the ios third party app internal page, I tried safari is no problem.

I'm not sure my description will allow you to reproduce the problem.

**Comment by auchenberg** [comment]
@zxerqw Thanks for the GIFs! 🔥  What kind of target are you debugging? Safari? UIWebView? WKWebView?

**Comment by zxerqw** [comment]
I emailed you the details

**Comment by auchenberg** [comment]
@zxerqw I think I found the issue. A new release of Inspect is building right now. 

Try to download the newest build in like 30-45min, and let me know if this fixes it for you.

**Comment by auchenberg** [comment]
https://inspect.dev/changelog/v0.7.8-fixes-broken-breakpoints

**Comment by zxerqw** [comment]
@auchenberg works for me, thanks for the quick fix!

**Comment by auchenberg** [comment]
Glad we got that woking!
