### ISSUE TITLE
page in safari can be detected but page in app can't.

### ISSUE THREAD

**Issue by haojian20161987** [inspectdev/inspect-issues#119]
- Inspect version: 0.7.7
- OS version and architecture: win32 x64 10.0.19043
- IOS: IOS 14.4.1

Steps to Reproduce:

    Install inspect
    Install iTunes
    Connect iPhone, let it sync with iTunes
    open page in safari, it's OK.
    open my app, but can't find webView in inspect.

**Comment by auchenberg** [comment]
@haojian20161987 What kind of WebView are you trying to debug? Inspect can't debug web views installed from the app store, but apps have to be with the local developer profile

**Comment by haojian20161987** [comment]
@auchenberg The app is installed by ipa file, not installed from the app store.

**Comment by auchenberg** [comment]
Inspect can only debug developer provisioned apps. See https://webkit.org/web-inspector/enabling-web-inspector/ for details.

**Comment by haojian20161987** [comment]
@auchenberg   thank you!
