### ISSUE TITLE
Core: Dark mode toolbar pops up, but clicking does nothing

### ISSUE THREAD

**Issue by NielsLeenheer** [inspectdev/inspect-issues#12]
- inspect-app version: 0.5.61
- OS ARCH VERSION: darwin x64 19.6.0
- Electron: 11.2.1
- Language: undefined

Steps to Reproduce:

1. Open a web page
2. Wait until the system changes from light to dark mode, or vice versa. The toolbar pops up.

<img width="727" alt="" src="https://user-images.githubusercontent.com/233230/109971582-b414e780-7cf6-11eb-97e2-4fb8bfd3438a.png">

**Comment by auchenberg** [comment]
Theme changes are disabled, so closing for now.
