### ISSUE TITLE
how to inspect over Wifi (on MacOS)

### ISSUE THREAD

**Issue by shenchaoran** [inspectdev/inspect-issues#125]
Hi, Inspect is very useful for me, but I want get rid of the USB cable, is there any docs about how to inspect over wifi ?

**Comment by auchenberg** [comment]
Open Safari on your Mac.

Make sure you enabled “Show Develop menu in menu bar” and enable Develop → <Your mobile Device Name> → Connect via Network in the menu. Now you can unplug the cable and check whether Develop → <Your mobile Device Name> still shows up on the desktop Safari.

Now close Safari, and Inspect will detect your devices.

**Comment by auchenberg** [comment]
Docs now available on https://inspect.dev/docs/guides/wifi

**Comment by shenchaoran** [comment]
thx
