### ISSUE TITLE
Typo in locked device notification (`Pleaee`)

### ISSUE THREAD

**Issue by jukibom** [inspectdev/inspect-issues#126]
- Inspect version: 0.7.8
- Electron: 15.3.4
- OS version and architecture: win32 x64 10.0.22000
- Language: undefined

Steps to Reproduce:

1. Connect device
2. Lock the device

![image](https://user-images.githubusercontent.com/5649179/150386253-0e078641-71cd-470e-8291-2471d873560b.png)

**Comment by auchenberg** [comment]
Good catch @jukibom. Fixed in next release
