### ISSUE TITLE
Nothing shows up in the inspector for devices running iOS 11 and 12

### ISSUE THREAD

**Issue by NielsLeenheer** [inspectdev/inspect-issues#13]
- inspect-app version: 0.5.61
- OS ARCH VERSION: darwin x64 19.6.0
- Electron: 11.2.1
- Language: undefined

Steps to Reproduce:

1. Open an iOS Simulator device with iOS 11 or 12
2. Open Safari and open a page
3. Nothing is visible in the Elements tab, nor in the Sources tab.

<img width="1499" alt="" src="https://user-images.githubusercontent.com/233230/109974559-fbe93e00-7cf9-11eb-927b-f08cb05cfd6f.png">

**Comment by auchenberg** [comment]
This should be resolved in the next build. Can I get you to validate @NielsLeenheer?

**Comment by auchenberg** [comment]
Validated with iOS 12.4 in the Simulator on Apple M1
