### ISSUE TITLE
Performance monitor - no data shown

### ISSUE THREAD

**Issue by nettermensch** [inspectdev/inspect-issues#131]
The tab "Performance monitor" does not show any data - the timeline is moving to the left, but no data is showing up.

Screenshot:
![2022-02-10 17_26_08-Inspect](https://user-images.githubusercontent.com/8876996/153451533-f817a4ec-7293-459a-bbee-bfa071206437.png)

Anything special that I have to do? Thx.

**Comment by auchenberg** [comment]
Performance tooling isn't supported at the moment. We will disable then Performance Monitor tool to reflect this.


Tracked in https://github.com/inspectdev/inspect-issues/issues/49
