### ISSUE TITLE
UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open '/opt/Inspect/resources/app-update.yml'

### ISSUE THREAD

**Issue by Warxcell** [inspectdev/inspect-issues#132]
node:451805) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open '/opt/Inspect/resources/app-update.yml'

Any ideas?

**Comment by auchenberg** [comment]
@Warxcell Can you provide some more details on when you are getting this? I assume you are on linux?

**Comment by Warxcell** [comment]
Yes, ArchLinux - it happens on Authentication.

**Comment by auchenberg** [comment]
Looks like something might be wrong with our auto updater. https://github.com/electron-userland/electron-builder/issues/4233

We'll dig into it.

**Comment by auchenberg** [comment]
@Warxcell We have upgraded electron-builder in the newest release. Does this still happen for you?

**Comment by Warxcell** [comment]
Sorry, lost context of this - I will go throught steps of installation and see what happens (hopefully in few days/weeks)

**Comment by dikdust** [comment]
still same problem on ubuntu 20.04, I guess it was the last update of the node. (I have used since last validation)
