### ISSUE TITLE
Debian package failed to install on Raspberry Pi

### ISSUE THREAD

**Issue by jinqiupeter** [inspectdev/inspect-issues#135]
The Debian package Inspect-0.7.8-linux-arm64.deb failed to install on the official Raspberry OS:
```
sudo apt install -y ./Inspect-0.7.8-linux-arm64.deb
Waiting for cache lock: Could not get lock /var/lib/dpkg/lock-frontend. It is held by process 1246 (apt)
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Note, selecting 'inspect-app:arm64' instead of './Inspect-0.7.8-linux-arm64.deb'
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 inspect-app:arm64 : Depends: libgtk-3-0:arm64 but it is not installable
                     Depends: libnotify4:arm64 but it is not installable
                     Depends: libnss3:arm64 but it is not installable
                     Depends: libxss1:arm64 but it is not installable
                     Depends: libxtst6:arm64 but it is not installable
                     Depends: libatspi2.0-0:arm64 but it is not installable
                     Depends: libuuid1:arm64 but it is not installable
                     Depends: libappindicator3-1:arm64 but it is not installable
                     Depends: libsecret-1-0:arm64 but it is not installable
E: Unable to correct problems, you have held broken packages.
```

The error says some package are missing, though the missing packages are installed, for example, the Inspect-dev packages depends on libgtk-3-0:**arm64**, but the exiting gtk-3.0 package has a different name:
![image](https://user-images.githubusercontent.com/12045814/156894606-e7041c3e-0308-48eb-ac96-86242d67d82e.png)

Is it possible to repack the Inspect-dev deb package to use the default names (for example to use gtk...-bin, rather than gtk....arm64) on Raspberry Pi?

Thank you!

**Comment by auchenberg** [comment]
We are using https://www.electron.build/configuration/linux to make Linux builds available, and I don't know enough about Linux/debian to make a call here.

@jinqiupeter Are you trying to use the ARM64 build on your RaspPi, which assumes ARM64 dependencies, but are have x86 versions?

**Comment by jinqiupeter** [comment]
Thanks for the reply! 
No I don't think my rPi has x86 version packages, the official rPi is ARM-based and its OS is Debian-based, I think it's about the naming of the dependencies.

What I am trying to achieve is to run a tool that depends on ios_webkit_debug_proxy, but according to Inspect.dev, ios_webkit_debug_proxy doesn't work for iOS 13+;  is it correct to assume that Inspect.dev can support all the commands that ios_webkit_debug_proxy supports?

**Comment by auchenberg** [comment]
@jinqiupeter No, Inspect is a UI based tool, that ships a standalone DevTools that the relevant adapters to enable iOS device communication, hence the need for `libgtk`. If you are looking for CLI based tool, there's currently no working alternative to `ios_webkit_debug_proxy`
