### ISSUE TITLE
Documentation and FAQ link from App resolves to Page Not Found

### ISSUE THREAD

**Issue by oddpixel** [inspectdev/inspect-issues#139]
- Inspect version: 0.7.9
- Electron: 15.3.4
- OS version and architecture: win32 x64 10.0.19041
- Language: undefined

Steps to Reproduce:

1. Click on Documentation and FAQ under Help
2. Goes to https://docs.inspect.dev/ and says Page Not Found

**Comment by auchenberg** [comment]
This will be fixed in next release
