### ISSUE TITLE
iOS: Simulator versions are not properly recognised 

### ISSUE THREAD

**Issue by NielsLeenheer** [inspectdev/inspect-issues#14]
I've got various versions of iOS open in the simulator: iOS 11.4, 12.1, 13.4 and 14.2. They are all recognised as 14.1.

<img width="299" alt="" src="https://user-images.githubusercontent.com/233230/109974729-2509ce80-7cfa-11eb-8420-446d962e052c.png">

However, my actual iPhone (wirelessly connected?!!) does show the right iOS version.

**Comment by auchenberg** [comment]
@NielsLeenheer Yup, this is a bit of a hack, as there's no official APIs to detect the Simulators, so lot of magic going on, including a hardcoded iOS version for simulators.

**Comment by wojtiku** [comment]
You can get iOS versions of the running simulators if you parse the output of `xcrun simctl list`.

P.S. You probably know this already @auchenberg - wrote it just in case it would be helpful.

**Comment by auchenberg** [comment]
@wojtiku Yup, just haven't hard time to get to it until today 🎊
