### ISSUE TITLE
DOM does not appear anymore

### ISSUE THREAD

**Issue by austinrscott** [inspectdev/inspect-issues#141]
- Inspect version: 0.7.9
- Electron: 15.3.4
- OS version and architecture: win32 x64 10.0.19043
- Language: undefined

Steps to Reproduce:

1. Had a successful session with Inspect, where everything loads properly and inspection highlighting appears as normal.
2. Go away/put computer to sleep/unplug and replug iPhone
3. Try to start a new session; the DOM initially appeared (in the Elements view of the DevTools inspector) but after trying to inspect a specific element on the page (a Vue component), the entire page became highlighted blue and stuck
4. Now I cannot get Inspect to work at all; I have tried restarting both Safari and Inspect, unplugging and replugging in the phone, etc. About to try restarting as well. If that solves it then I will update this issue with that info. Inspect appears to see my iPhone on the left side but it cannot show me the DOM in the Elements tab (it's just blank)

**Comment by austinrscott** [comment]
After restarting my machine, I loaded the website up again with Inspect. I was able to see the DOM appear again, and I tried once more to inspect the same element. Inspect is now frozen. Here is a screenshot of the portion of the DOM I was trying to inspect when it failed: 
![image](https://user-images.githubusercontent.com/6800247/162753151-4515e57f-b58a-417a-b427-6c142dd4e34f.png)

**Comment by auchenberg** [comment]
@austinrscott Sorry about this. What kind of Target are you trying to debug with Inspect? Safari? Webview?

It it be possible for you to share the URL, so we can debug this on our end?

**Comment by austinrscott** [comment]
> @austinrscott Sorry about this. What kind of Target are you trying to debug with Inspect? Safari? Webview?
> 
> It it be possible for you to share the URL, so we can debug this on our end?

I’m trying to use Inspect with Safari on iOS 14.8.1 with an iPhone XR. I am using a lightning cable hooked up to a USB3 port on a Windows 10 PC. Unfortunately I can’t share, as it’s on my private VPN, but it appears inspect is still breaking on it and we will be pushing this code to production soon, so I will hopefully be able to share within the next few weeks.

**Comment by auchenberg** [comment]
@austinrscott Okay. Can I get you to start your command prompt on Windows and try to start the `inspect.exe` binary from within the terminal? This should enable debug mode and output the logging in the console.

Please attach the output here.

Lets see what happens. It sounds like a crash

**Comment by austinrscott** [comment]
I fixed the bug I was working on, and I also shut down my computer last night; somewhere between those two things, I have not been able to reproduce this bug with Inspect anymore. I was able to run in the console and receive debugging output, but the bug didn't occur this time. I'll run it from the command line again next time it happens and send you the results

**Comment by auchenberg** [comment]
Very interesting @austinrscott I'll close the issue for now, and if it occurs again lets debug this.
