### ISSUE TITLE
Fix Help > Documentation and FAQ

### ISSUE THREAD

**Issue by Zibx** [inspectdev/inspect-issues#142]
- Inspect version: 0.7.9
- Electron: 15.3.4
- OS version and architecture: win32 x64 10.0.19044
- Language: undefined

Steps to Reproduce:

1. In the main app click Help menu > Documentation and FAQ
2. https://docs.inspect.dev/ would open and says that Page Not Found. And while it is loading it would show the content for the small amount of time

Possible fixes:

- Change the URL to https://docs.inspect.dev/docs/
- Make redirect from https://docs.inspect.dev/ to https://docs.inspect.dev/docs/
- Do not change content of old page to "Page Not Found"

**Comment by auchenberg** [comment]
Thanks for the report @Zibx. This will be fixed in next release
