### ISSUE TITLE
 ELECTRON_IS_DEV 1 in my environment seems to mess app up.

### ISSUE THREAD

**Issue by josh-manton** [inspectdev/inspect-issues#144]
My Ionic React SPA forwards to Microsoft AD B2C for authentication https://docs.microsoft.com/en-us/azure/active-directory-b2c/overview. Inspect is able to follow the forward but is unable to render the B2C page. When I view the source, it contains the full markup but the markup does not render. This may be due to the fact that you are not forwarding required headers, cookies or perhaps not executing the javascript. Further investigation is required. I'm happy to work with you to resolve this issue.

**Comment by josh-manton** [comment]
Update: I was running in a broken mode because I had ELECTRON_IS_DEV 1 in my environment. We are developing an electron app and we use the for debugging. You must have a check for that flag in your code? Removing the environment variable gave me the proper interface and i'm able to get things working.

**Comment by auchenberg** [comment]
@josh-manton Glad you got going! We are indeed an Electron based app, so lets look into this.
