### ISSUE TITLE
Network traffic not showing up for WKWebView on iOS 15.2 Simulator

### ISSUE THREAD

**Issue by enk0de** [inspectdev/inspect-issues#145]
on Safari Technology Preview, it works well. but on inspect, it isn't working.

**Comment by auchenberg** [comment]
Are you trying to use Safari together with Inspect? Only one dev tool can be connected at a time, so try to close your Safari instance if devices can't be detected.

**Comment by enk0de** [comment]
No. i used only one inspector (Inspect App). the problem is that **network activity is not captured** even though inspecting instance is available on Inspect App.

**Comment by auchenberg** [comment]
Okay, so network activity is the problem. What kind of app are you trying to debug with Inspect? Safari? Webviews?

**Comment by enk0de** [comment]
WKWebView!

**Comment by auchenberg** [comment]
Alright, so what are you trying to do more specifically? You connect Inspect to your WKWebView and dont' see any network traffic?

**Comment by enk0de** [comment]
yes it is.
- connect inspect to my wkwebview
- and can't see any network traffic

**Comment by auchenberg** [comment]
Closing this, as we don't see the problem with wkwebview's on iOS 17.5.1
