### ISSUE TITLE
Windows 10 + iOS15.5: Inspect loads new data when opened, but does not update 

### ISSUE THREAD

**Issue by jmcelfresh** [inspectdev/inspect-issues#147]
Inspect shows my iPhone under Available Devices and allows me to view the console logs. When I begin interacting with a website on my iPhone the console does not change. However if I close and reopen Inspect, the new logs show up. 

Any suggestions how to troubleshoot this?

**Comment by auchenberg** [comment]
@jmcelfresh That's an interesting problem. Is it just the `console` that doesn't work or is it all of the tools within Inspect?

Try to enable the Protocol Monitor and paste the log in here

<img width="1552" alt="Screen Shot 2022-07-16 at 7 31 52 PM" src="https://user-images.githubusercontent.com/173559/179381457-68d661d2-5232-4cb2-813a-06c29d4205bc.png">
