### ISSUE TITLE
Expanding objects in Console does not work

### ISSUE THREAD

**Issue by zhang2333** [inspectdev/inspect-issues#148]
- Inspect version: 0.8.2
- Electron: 19.0.3
- OS version and architecture: darwin x64 20.6.0
- Language: undefined

Steps to Reproduce:

1. Open any website in iOS Safari (Google in the screenshot)
2. Create any objects in Console, and expand it

The detail of the object is "No properties", not its content.

<img width="563" alt="image" src="https://user-images.githubusercontent.com/10372448/180409838-d98405e1-300a-462b-a29c-728183eed3d2.png">

**Comment by ajck** [comment]
This bug includes logged objects during program runtime, e.g. in your code you have `console.log(someObject)` not just ones newly created live in the console on the console command line.

**Comment by nitedani** [comment]
Same issue here. Can't expand objects in Safari console.

**Comment by auchenberg** [comment]
This issue should have been resolved
