### ISSUE TITLE
Inspect does not remove targets that have been killed by Xcode

### ISSUE THREAD

**Issue by NielsLeenheer** [inspectdev/inspect-issues#15]
- inspect-app version: 0.5.61
- OS ARCH VERSION: darwin x64 19.6.0
- Electron: 11.2.1
- Language: undefined

Whenever I work on our Cordova app, I regularly switch between coding, compiling in Xcode and running it in the simulator. After seeing the result, I go back to coding, then compiling again and running it again. Every time I go to this process, the old app is killed in the simulator to be replaced by the newly compiled version. 

Inspect however keeps the old targets around. It does not remove them from the list after they have been killed by Xcode. So after going through a few rounds of this a long list of dead targets accumulate.

<img width="304" alt="" src="https://user-images.githubusercontent.com/233230/109979639-6486e980-7cff-11eb-9bdd-ce317a166cc3.png">

**Comment by auchenberg** [comment]
Should be fixed in next update! Thanks for reporting 🙇
