### ISSUE TITLE
No debuggable apps found

### ISSUE THREAD

**Issue by BerciTheBeast** [inspectdev/inspect-issues#150]
- Inspect version: 0.8.2
- Electron: 19.0.3
- OS version and architecture: win32 x64 10.0.19042
- Language: undefined
- Device: iPhone 11

Steps to Reproduce:

1. Follow connection steps on Inspect
2. Open Safari on iPhone.
3. Navigate to Vue3 app address hosted over local network
4. Attempt to find Safari instance on Inspect, fail.

**Comment by BerciTheBeast** [comment]
I would try removing the device from the list and connecting it again, but I have yet to find a way to remove it.

**Comment by auchenberg** [comment]
Hi there,

Do you see the browser tab within Inspect? Do you see your device?

**Comment by BerciTheBeast** [comment]
Hi, I just went back to check, and Inspect showed me everything running in Safari, so it works now. If I remember correctly, it did show the device and the browser, but when clicking the browser it said something along the lines of "no inspectable elements found" or something like that (cannot reproduce at the moment, and I have 1 day left in my trial :/ ).

**Comment by sturlath** [comment]
Just bought this for iOS and I have the same issue.. can see my phone but no debuggable app found. I can view my phone in iTunes and everything looks good.

But maybe I´m doing something wrong so few questions

1. What is a debuggble app?
2. Is it just Safari browser?
3. Or can I run my IDE (Visual Studio/Code) and access that code in the browser
4. Is the only thing needed (except the settings you take us through in the documentation) is to open up Safari en have some browser tab open?

Btw I´m on Windows with an iPhone

**Comment by EarMaster** [comment]
I have the same problem. iPad is available in the list, but "No debuggable apps found."
Dev settings for Safari are enabled and I have several tabs open, I also have some apps using WebViews which are debuggable on Macs.

**Comment by RafidMuhymin** [comment]
@auchenberg I am facing the same issue with iPhone 14 Pro Max.

**Comment by RafidMuhymin** [comment]
I found that actually Safari has to be opened on iPhone first before opening Inspect. It would be better if Inspect could detect it automatically.
