### ISSUE TITLE
Network tab doesn't show list of requests

### ISSUE THREAD

**Issue by sammytran90** [inspectdev/inspect-issues#152]
- Inspect version: 0.8.2
- Electron: 19.0.3
- OS version and architecture: win32 x64 10.0.19043
- Language: undefined

Device: iPhone SE2020 - iOS 15.6.1

Steps to Reproduce:

1. Open ITunes (connected with device via Wifi)
2. Open Inspect
3. Open Safari browser on device
4. Open a website
5. Check network tab

Results:
- Network tab doesn't show request
![image](https://user-images.githubusercontent.com/32162425/188275081-54fe7ed8-e7fc-4c3d-9503-3fa27e95e47d.png)

**Comment by sammytran90** [comment]
`Has blocked cookies` was checked which filtered the list of requests.

**Comment by auchenberg** [comment]
Glad you got it resolved!
