### ISSUE TITLE
How to proceed if no iTunes for Mac OS Monterey?

### ISSUE THREAD

**Issue by vahanavagyan** [inspectdev/inspect-issues#158]
- Inspect version: 0.8.2
- Electron: 19.0.3
- OS version and architecture: darwin arm64 21.1.0
- Language: undefined

Steps to Reproduce:

1.
2.

**Comment by auchenberg** [comment]
Inspect relies on the official drivers from Apple, which are provided by iTunes

You might be able to use the open source driver from https://libimobiledevice.org
