### ISSUE TITLE
When selecting an element to inspect it, the element is not selected in the Elements tab

### ISSUE THREAD

**Issue by NielsLeenheer** [inspectdev/inspect-issues#16]
- inspect-app version: 0.5.61
- OS ARCH VERSION: darwin x64 19.6.0
- Electron: 11.2.1
- Language: undefined

Steps to Reproduce:

1. Click on the icon for selecting an element in the toolbar
2. It now turns blue
3. Go to the simulator
4. Click on an element
5. Nothing happens...

What I expect to happen is that the element I clicked on is now selected in the Elements tab

https://user-images.githubusercontent.com/233230/109980561-55546b80-7d00-11eb-8e1e-c1069fb8606e.mov

**Comment by auchenberg** [comment]
Really good catch, probably an API that hasnt been mapped. Thanks for this high quality bug report @NielsLeenheer

**Comment by auchenberg** [comment]
Fixed, should be working in next release!
