### ISSUE TITLE
Support signups from China (Google limitations)

### ISSUE THREAD

**Issue by AntonOfTheWoods** [inspectdev/inspect-issues#160]
Hi, it looks like you are using Google infrastructure, that is mostly blocked from China. Is there some other way to use the software?

**Comment by auchenberg** [comment]
Thanks for the report @AntonOfTheWoods . 

Not at the moment. We rely on Google Firebase for authentication.

**Comment by furuskog** [comment]
Google, share information with the american goverment. I dont want my information shared with them. My works policy does not allow that. So it would be good i you were GDPR complient.

**Comment by auchenberg** [comment]
@furuskog This is all outlined in our privacy notice, https://inspect.dev/privacy

**Comment by AntonOfTheWoods** [comment]
@auchenberg , it's not just signups - if I am in the US for signing up and then go to China, I am unable to use the service (without a VPN), right?

**Comment by auchenberg** [comment]
@AntonOfTheWoods @furuskog We have now updated our authentication system and it has moved off Google.

**Comment by AntonOfTheWoods** [comment]
Yup, just about a year too late for me unfortunately

**Comment by auchenberg** [comment]
Better late than never!
