### ISSUE TITLE
Feature Request: Use VS Code to debug

### ISSUE THREAD

**Issue by hediet** [inspectdev/inspect-issues#166]
I love this tool!

Would be awesome if I could use VS Code instead of chrome dev tools to debug the page.
Does inspect.dev open a port VS Code js debug could attach to?

Thanks!

**Comment by auchenberg** [comment]
Happy to hear this @hediet!

Not at the moment, but it's a great idea, and something we are considering doing.

Tracked in https://github.com/inspectdev/inspect-issues/issues/59
