### ISSUE TITLE
No debuggable app found for WebViews on iOS 16.2 and beyond

### ISSUE THREAD

**Issue by fanninghau** [inspectdev/inspect-issues#168]
I am debugging a Cordova app on an iPhone which is iPhone 6Plus iOS 14.3. It's working well. But I change the phone which is iPhone 14 Pro iOS 16.2 and open my Cordova app, it shows "No debuggalbe app found". Btw when I open the safari on iPhone 14Pro, it shows something. Any ideas?

**Comment by vitor-diego-s** [comment]
Here the same issue on IOS 16.3.1

**Comment by losmurfs** [comment]
Still "No debuggable apps found." in iOS 16.4.1. I really want to pay for this software, but I won't until I can get it to work.

**Comment by riderx** [comment]
it's not linked to the software but to a change in ios.
https://developer.apple.com/forums/thread/727049

**Comment by FryDay** [comment]
So if Inspect is unable to work around this, the app is effectively useless now?

**Comment by losmurfs** [comment]
That's what it sounds like, "it's not us, it's iOS", so it's useless.

**Comment by riderx** [comment]
guys i'm just a client like you and it work just read the issue in apple website and do the fix it's necessary to do in your app it's 5 sec 😂

**Comment by losmurfs** [comment]
Cool, so webView will always be instantiated? If I'm trying to inspect on
windows can I just include the following in JavaScript?: const webView =
{inspectable: true}; // ignore wrong names for now

**Comment by FryDay** [comment]
> do the fix it's necessary to do in your app it's 5 sec

And if it's a PWA you are trying to debug? What's the fix for that?

**Comment by riderx** [comment]
i use capacitor for cordova you can check the issue here: https://github.com/apache/cordova-ios/issues/1301

**Comment by auchenberg** [comment]
Hi everyone,

Kenneth here from Inspect. I do apologize the late response here. 

We have looked into this and regular PWA debugging continues to work on iOS 14.6.1 with Inspect, but for apps that are wrapping <webview> content in a native shell, you indeed need to make them inspectable by following the guide provided by Apple: https://webkit.org/blog/13936/enabling-the-inspection-of-web-content-in-apps/

Inspect relies on the APIs and drivers provided by Apple, and this is an iOS-level change that apps needs to adopt to. 

We hope this change in iOS also makes it possible for Inspect to debug browsers like Google Chrome, but we don't know yet.

Thank you.

**Comment by FryDay** [comment]
> We have looked into this and regular PWA debugging continues to work on iOS 14.6.1 with Inspect, but for apps that are wrapping content in a native shell, you indeed need to make them inspectable by following the guide provided by Apple: https://webkit.org/blog/13936/enabling-the-inspection-of-web-content-in-apps/

I suppose that depends on your definition of "debugging". In iOS 16.4.1, I am unable to inspect elements of a PWA. All I can do is see and work with the service worker.

**Comment by auchenberg** [comment]
Validated that the PWA https://starbucks.com is debuggable on iOS 17 after being saved to the home screen. Closing.
