### ISSUE TITLE
Element select doesn't work 

### ISSUE THREAD

**Issue by TheNathanHernandez** [inspectdev/inspect-issues#17]
- inspect-app version: 0.5.61
- OS ARCH VERSION: win32 x64 10.0.19042
- Electron: 11.2.1
- Language: undefined

Element select fails to work. Not sure if this is just how WebKit is designed when it's not on a regular Mac or if it's just Chromium and it's failure to interpret the source code in the case of it's ability to be able to select the element but I'd just like to quickly mention how much of an amazing app this is! This is just a feature I use a ton and I would natively consider it essential! Thanks!

**Comment by auchenberg** [comment]
@TheNathanHernandez What version of IOS and device are you using? What kind of app? Regular safari tab? Cordova?

**Comment by auchenberg** [comment]
Making as dup of https://github.com/inspectdev/inspect-issues/issues/16

**Comment by TheNathanHernandez** [comment]
> @TheNathanHernandez What version of IOS and device are you using? What kind of app? Regular safari tab? Cordova?

Completely stock Safari, regular tab, iOS 14.5 / iPhone Xs.
