### ISSUE TITLE
console.warn() and console.error() does not show messages

### ISSUE THREAD

**Issue by SuperPat45** [inspectdev/inspect-issues#172]
Using inspect.dev 0.8.2 and iOS 16.4

The console.warn(msg) and console.error(msg) functions does not show messages only an empty line:
![image](https://user-images.githubusercontent.com/7791600/228853377-4005d094-9c51-4a61-8a0f-7e1bf5a64dae.png)

console.log(msg) et console.info(msg) works fine

**Comment by auchenberg** [comment]
Happy to announce that this will be fixed in the next update to Inspect 🎉 

Refs #183
