### ISSUE TITLE
theme does not stay memorized

### ISSUE THREAD

**Issue by planeth44** [inspectdev/inspect-issues#176]
- Inspect version: 0.7.9
- Electron: 15.3.4
- OS version and architecture: linux x64 5.15.0-71-generic
- Language: fr_FR.UTF-8

Steps to Reproduce:

1. Go to settings > appearance > theme > light
2. restart Inspect, theme is light
3. Click on other link in the left sidebar > theme goes dark again.

This is super annoying when you cannot work with dark mode.

**Comment by auchenberg** [comment]
We don't support light themes at the moment, but this is on the backlog. Tracked in https://github.com/inspectdev/inspect-issues/issues/157
