### ISSUE TITLE
Console is missing errors

### ISSUE THREAD

**Issue by auchenberg** [inspectdev/inspect-issues#180]
> I can't see errors/warnings anymore

![image](https://github.com/inspectdev/inspect-issues/assets/173559/7c0eccc7-5926-44e3-a06b-a0fdecf268d0)

**Comment by auchenberg** [comment]
Another user:

> I’m having an issue where I can see there are errors on my page on iPad, but I cannot actually see them in the inspector – they look to be collapsed or else have no actual content:
I think the errors and warnings should be where the red and amber lines are, but they have no content.

![image](https://github.com/inspectdev/inspect-issues/assets/173559/d913cd1c-1ffb-4360-a9a9-31dffeb0d493)

**Comment by riderx** [comment]
Same for me and 5 person of my team

**Comment by alsatian** [comment]
I have the same issue, practically not worth paying for something that doesn't show errors and warnings, when is the fix coming?
- Inspect version: 0.8.2
- Electron: 19.0.3
- OS version and architecture: win32 x64 10.0.19045

**Comment by auchenberg** [comment]
Happy to announce that this will be fixed in the next update to Inspect 🎉 

Refs #183
