### ISSUE TITLE
Error messages are not shown

### ISSUE THREAD

**Issue by matthiasnordwig** [inspectdev/inspect-issues#183]
- Inspect version: 0.8.2
- Electron: 19.0.3
- OS version and architecture: win32 x64 10.0.19045
- Language: undefined

Steps to Reproduce:

1. I am using iPhone 13
2. I can see that an error occures, and the chatlog is highlightet red, but it doesn't contain any text

![error_messages are empty](https://github.com/inspectdev/inspect-issues/assets/146366359/eaf96585-6669-47bb-b136-e01e0a108f52)

**Comment by JavaScriptDude** [comment]
I'm seeing the same thing debugging iPhone 14 on Linux. All regular logs are shown but no errors. Errors are being displayed as thin red lines.

**Comment by agsti** [comment]
It's a hack but I managed to see the errors by doing:
```
console.error = console.log
console.warn = console.log
```

**Comment by JavaScriptDude** [comment]
I wonder if there is a way to coerce the debugger used so this hack could be somewhat 'automated'.

**Comment by nicraf** [comment]
Is this product no longer support/updated? Was a great tool but has not been updated since June 2022.  needs to be updated to new macOs/iOS etc

**Comment by auchenberg** [comment]
Happy to announce that this will be fixed in the next update to Inspect 🎉

**Comment by JavaScriptDude** [comment]
Thanks for fixing this. I am considering purchasing this but just wanted to make sure that this type of show stopper bug does not linger for several months in the future.

**Comment by auchenberg** [comment]
@JavaScriptDude We are trying out best to keep a steady ship cycle here in 2024 and beyond!
