### ISSUE TITLE
The xcodebuild dialog opens and freezes

### ISSUE THREAD

**Issue by R-Az** [inspectdev/inspect-issues#184]
- Inspect version: 0.8.2
- Electron: 19.0.3
- OS version and architecture: darwin x64 23.1.0
- Language: JP
- xcodebuild version: 
  - Xcode 14.3.1 Build version 14E300c
  - Xcode 15.2 Build version 15C500b

When launching Inspect, a software installer triggered by xcodebuild appears, causing it to freeze. Despite multiple Mac restarts, the issue persists consistently. 
Additionally, the ability to connect to the iPhone, which was working before, is now affected since the onset of this problem.
Safari connectivity remains unaffected, leading to the belief that the issue is specific to Inspect.

Steps to Reproduce:

1. Launch Inspect.
2. Open the xcodebuild dialog.
  ![image](https://github.com/inspectdev/inspect-issues/assets/76928850/7ebc41b5-5ff6-4b7c-9ae5-8b19d455c765)
3. Click on the software install option.
4. The xcodebuild dialog freezes.

Troubleshooting Steps Taken:
- Reinstallation of Inspect.
- Switching xcode versions.
  - Downgraded from 15.2 to 14.3.
- Mac restarts.
- Inspect app actions:
  - Restart.
  - Log out and log back in.
  - Reset.
- Killing xcodebuild processes.
- Killing SecurityAgent processes (xcodebuild dialogs).

Additional Information:
- Multiple xcodebuild processes are running in the background.

```sh
pgrep 'xcodebuild' -l

32570
32592
32637
32682
32736
...etc
```

**Comment by R-Az** [comment]
I apologize for the inconvenience. 
The issue I encountered was a result of upgrading Xcode due to the OS update. 
With the OS update, there is now a requirement for licensing agreement acceptance for Xcode or xcodebuild. 
It appears that the freezing occurred because this agreement was not acknowledged.

The solution is as follows. I apologize for any trouble this may have caused.

```sh
sudo xcodebuild -license
```

**Comment by auchenberg** [comment]
Thank you so much for sharing this @R-Az. This will be helpful for other users of Inspect.
