### ISSUE TITLE
Not possible to edit the style of an element using the Styles sidebar

### ISSUE THREAD

**Issue by NielsLeenheer** [inspectdev/inspect-issues#19]
- inspect-app version: 0.5.66
- OS ARCH VERSION: darwin x64 19.6.0
- Electron: 11.2.1
- Language: undefined

It is currently not possible to edit the css properties of an element directly using Styles sidebar. In the Chrome Dev Tools there is usually a section called element.style { ... } that contains all the CSS properties defined in the styles attribute of the element. Similarly in de Safari Web Inspector called Style Attribute { .. } containing the same CSS properties.

This section is missing in Inspect, which means you have to edit the style attribute directly in the element tree.

For example: in the screenshot below, you'll see the HTML element has a style attribute. But the Styles sidebar does not have a section to edit those CSS properties.

<img width="1718" alt="Screenshot 2021-03-08 at 11 00 36" src="https://user-images.githubusercontent.com/233230/110306746-75d13e00-7ffe-11eb-9a20-a9a645a98d2c.png">

**Comment by auchenberg** [comment]
![](https://user-images.githubusercontent.com/4060795/112343391-76720180-8c99-11eb-8281-60d8621780ee.png)
