### ISSUE TITLE
iOS device not visible with Windows 10 PC

### ISSUE THREAD

**Issue by daczczcz1** [inspectdev/inspect-issues#190]
- Inspect version: 1.0.4
- Electron: 27.1.3
- OS version and architecture: win32 x64 10.0.19045
- Language: undefined
- device: iPhone 12. iOS 17.2.1
Steps to Reproduce:

1. Install app
2. Connect device

"No devices found" - hitting "re-run setup" doesn't do anything. Moreover, there is a prompt asking whether to allow access to Photos, but no prompt asking to "trust computer" (which I was getting when using the Linux version).

**Comment by daczczcz1** [comment]
Please ignore - missed installing iTunes

**Comment by auchenberg** [comment]
@daczczcz1 Glad you got going!
