### ISSUE TITLE
Download Debian Resolves to arm64 File

### ISSUE THREAD

**Issue by JavaScriptDude** [inspectdev/inspect-issues#191]
I am running Debian desktop but the `Download Debian` link downloads an arm64 file and not amd64.

If amd64 is not available for debian, please update the download page to say `Download Debian (arm)`

**Comment by auchenberg** [comment]
@JavaScriptDude Let us see if we can't find a way to provide both for you. Stay tuned.

**Comment by auchenberg** [comment]
We now have the following builds available:
- Debian arm64: https://download.inspect.dev/builds/240303op25cr74z/linux/deb/arm64
- Debian x64: https://download.inspect.dev/builds/240303op25cr74z/linux/deb/x64

**Comment by JavaScriptDude** [comment]
FYI - Both links resolve to the same arm64 file. No amd64 file is available.

Secondly, is there any instructions on how to install the .snap package? All the snapcraft stuff I've seen is installed using `snap` command.

**Comment by JavaScriptDude** [comment]
FYI - I have a new OS based on the latest Mint and was able to get it working with the `AppImage` file.

**Comment by auchenberg** [comment]
Our vendor who provides out build infrastructure has been made aware of the problem, and is working on a fix. Stay tuned.

**Comment by auchenberg** [comment]
This has been resolved and deployed.
