### ISSUE TITLE
My app is not debugging anymore

### ISSUE THREAD

**Issue by lbsesouza** [inspectdev/inspect-issues#194]
- Inspect version: 1.0.4
- Electron: 27.1.3
- OS version and architecture: win32 x64 10.0.22631
- Language: undefined

Steps to Reproduce:

1. Plug device
2. Window recognize
3. Open App
4. Not shown at Inspect, the same app that was showing few hours before

**Comment by auchenberg** [comment]
Try to grab the latest release from https://inspect.dev/download

**Comment by lbsesouza** [comment]
Already tried the new version 1.0.5. Restart my pc. Restart my phone.
Rebuild the app with voltbuilder. Check if Safari inspect was on etc. The
device is not recognized anymore. My phone shows on My computer but not at
inspect
Luiz Bernardo Souza e Souza
Sócio e Engenheiro do sistema Appraise Cloud - Mobile

(75) 99231-5646  |  appraisecloud.com.br


Em qua., 20 de mar. de 2024 às 04:36, Kenneth Auchenberg <
***@***.***> escreveu:

**Comment by lbsesouza** [comment]
Nevermind, just tried and its working back again
Luiz Bernardo Souza e Souza
Sócio e Engenheiro do sistema Appraise Cloud - Mobile

(75) 99231-5646  |  appraisecloud.com.br


Luiz Souza ***@***.***> escreveu (quarta, 20/03/2024
à(s) 10:11):
