### ISSUE TITLE
Kagi extension breaks Inspect

### ISSUE THREAD

**Issue by joshuaiz** [inspectdev/inspect-issues#195]
Hello,

I recently installed the Kagi search extension for Safari on iOS and now when my device is plugged in to my MBP Inspect seems pretty borked. 

I cannot inspect any html on any site and not all open tabs are mounted in Inspect. 

Would love to continue to use Kagi but if it is not working with Inspect, I might have to remove.

Best,

Joshua

**Comment by joshuaiz** [comment]
And I can confirm Inspect works as expected with Kagi disabled.

**Comment by auchenberg** [comment]
@joshuaiz Very interesting. 

Would it be possible to share a screenshot of how borked Inspect looks?

**Comment by joshuaiz** [comment]
Welp, I just re-enabled the Kagi extension in iOS Safari settings and everything seems to work in Inspect as expected. ¯\_(ツ)_/¯ Perhaps it wasn't loaded correctly before.

I will close this but if I run into anything else with this extension will open another issue.

**Comment by auchenberg** [comment]
@joshuaiz Funky. Well keep us posted, and hopefully we can figure out what's happening
