### ISSUE TITLE
Windows installer triggers Microsoft Defender SmartScreen

### ISSUE THREAD

**Issue by Discostu36** [inspectdev/inspect-issues#198]
When installing Inspect on Windows, Microsoft Defender SmartScreen gives a warning about a potentially dangerous app.

![image](https://github.com/inspectdev/inspect-issues/assets/30999326/d7dee5ae-09d7-4da8-bc8b-5164c41a6281)

**Comment by auchenberg** [comment]
@Discostu36 Thanks for the report! 

This happens when we release a new build. Please mark the file as trust worthy, and it will help get the Inspect ratings up.
