### ISSUE TITLE
Not possible to move the cursor to top lines when editing multi-line attribute

### ISSUE THREAD

**Issue by NielsLeenheer** [inspectdev/inspect-issues#20]
- inspect-app version: 0.5.66
- OS ARCH VERSION: darwin x64 19.6.0
- Electron: 11.2.1
- Language: undefined

Steps to Reproduce:

1. Open a page that contains an element with a very large attribute.
2. Double click that attribute. 
3. Editing mode is enabled, the contents is now selected
4. Click somewhere in the text of the attribute
5. The cursor is placed in position you clicked, allowing you to type text
6. Click somewhere in any of the lines, except the last one. 
7. You expect the cursor to move there... but it does not, it leaves editing mode.

Now this works for the last line. Not for any of the other lines. Meaning it is very difficult to edit large attributes.

In the video below that is exactly what I am doing. First I am trying the bottom line and it works. Then I am clicking the middle and top line and instead of moving the cursor, it leaves editing mode altogether.

Just to be sure this isn't a bug in the Chrome Dev Tools, I've also tried this in the browser and there it works without any problem. The cursor also moves when you click in the top of middle lines of the attribute.

https://user-images.githubusercontent.com/233230/110308222-27bd3a00-8000-11eb-9f49-77a0341173fa.mov

**Comment by auchenberg** [comment]
@NielsLeenheer This should have been resolved in the next release. Fixed by upgrading Electron.

https://user-images.githubusercontent.com/173559/117603615-6f4b6980-b108-11eb-838d-a935500b0461.mov
