### ISSUE TITLE
debugging exceeded message shown at pro account. 

### ISSUE THREAD

**Issue by MirjamDG** [inspectdev/inspect-issues#203]
- Inspect version: 1.0.9
- Electron: 27.1.3
- OS version and architecture: win32 x64 10.0.19045
- Language: undefined

Steps to Reproduce:

1. I am logged in with my account. I have an inspect pro account. still i get the message 'debugging exceeded'. I cannot debug anymore. 
2.

**Comment by auchenberg** [comment]
Try to log out of your account in the Inspect app, and login again

Menu -> Help/Inspect -> log out
