### ISSUE TITLE
Core: Allow multiple Inspect windows open at the same time

### ISSUE THREAD

**Issue by NielsLeenheer** [inspectdev/inspect-issues#21]
What I would love is have the ability to use Inspect at the same time for multiple targets at once. A "simple" solution would be to allow multiple Inspect windows to open. Select one device in the first window, select the other device in the second window. Even better would be being able to right-click on the list of devices and select "Open in new Window" or something similar.

Especially for debugging a problem that only happens on certain devices, that would be really helpful.

**Comment by auchenberg** [comment]
Won't be possible due to the nature of how the Apple IOS driver works. Only one connection at the time, so closing.
