### ISSUE TITLE
There is a subscription, but Inspect app doesn't "see" it

### ISSUE THREAD

**Issue by alexyakunin** [inspectdev/inspect-issues#213]
- Inspect version: 0.8.2
- Electron: 19.0.3
- OS version and architecture: win32 x64 10.0.22631
- Language: undefined

Steps to Reproduce:

1. Open Inspect app

It shows "Buy inspect now", even though I have a subscription.

**Comment by auchenberg** [comment]
@alexyakunin Your login session might have expired. Can you try to log out of the app, and login again?

**Comment by alexyakunin** [comment]
It works now, but earlier logging out & logging in didn't change anything.
