### ISSUE TITLE
Cut, copy and paste does not work

### ISSUE THREAD

**Issue by NielsLeenheer** [inspectdev/inspect-issues#22]
- inspect-app version: 0.5.66
- OS ARCH VERSION: darwin x64 19.6.0
- Electron: 11.2.1
- Language: undefined

Right now it is impossible to cut and copy text from Inspect, or paste into Inspect. 

a) The Edit menu is not available in the main menu bar. 
b) The Command-X, Command-C and Command-V shortcuts do not work either.
c) Right-clicking the text does not give a context menu with Cut, Copy and Paste commands either.

It usually pretty easy to solve a) and b) by adding an Edit menu to your applications menu bar and declaring the appropriate menu items with a specific role.

**Comment by yannbf** [comment]
I second this. I think it could be related to certain keyboard events not being correctly propagated
