### ISSUE TITLE
Make name of target in the list of devices easier to distinguish 

### ISSUE THREAD

**Issue by NielsLeenheer** [inspectdev/inspect-issues#23]
The name of the target is current the URL, which can be pretty long. And if you are testing multiple targets on the same domain they would be all identical, because the URL for all targets would start with domain and maybe even path.

<img width="456" alt="Screenshot 2021-03-08 at 17 20 52" src="https://user-images.githubusercontent.com/233230/110349425-fd38a480-8032-11eb-975d-434c0274d7f7.png">

Perhaps it would be better to use something similar what Safari is currently is doing.

<img width="410" alt="Screenshot 2021-03-08 at 17 21 47" src="https://user-images.githubusercontent.com/233230/110349709-3ffa7c80-8033-11eb-82d2-cae29806e310.png">

Safari shows just the domain name and the filename of the URL. And when you hover over it, it shows the full URL in a tooltip.

**Comment by auchenberg** [comment]
@NielsLeenheer How about using the page title? Would that work for your scenarios?

**Comment by auchenberg** [comment]
Using page title for now, and full url for hover

**Comment by joshuaiz** [comment]
@auchenberg Came to find how to view the full url so this is helpful.

Feature request: to be able to right-click the title to copy the full url. Currently there is no way to do that...sometimes I need to copy + paste to compare.

**Comment by auchenberg** [comment]
@joshuaiz Great idea. Can I get to open a new issue for this https://github.com/inspectdev/inspect-issues/issues/new? I want you to get the credit when we land the feature.
