### ISSUE TITLE
iOS: Add support for Chrome on iOS inspection

### ISSUE THREAD

**Issue by chrisribe** [inspectdev/inspect-issues#24]
Works fine for Safari but I am looking for a way to inspect the ChromeBrowser app on an IOS device.
Adding that would be a godsend !

- inspect-app version: 0.5.66
- OS ARCH VERSION: darwin x64 19.6.0
- Electron: 11.2.1
- Language: undefined

**Comment by auchenberg** [comment]
This is sadly blocked on Apple not allowing apps via the App Store to be debuggable. Not much to be done, until this changes or a workaround is found.

**Comment by NewSense21** [comment]
You can only inspect WebKit targets on iOS and Chrome uses Blink, that's why the issue. Use chrome://inspect on iOS Chrome if you just want to collect JS console logs from all tabs.

**Comment by azertyalex** [comment]
There is only one Webengine on iOS. Chrome on iOS is just WebKit with another skin. Not chromium

**Comment by hirokith** [comment]
Good news, webkit finally supported remote inspection on released apps since iOS@16.4: https://webkit.org/blog/13936/enabling-the-inspection-of-web-content-in-apps/

**Comment by auchenberg** [comment]
We're thrilled to announce that Inspect can now debug Chrome on iOS, which has been one of our most requested features since the launch of Inspect!

Read more here: https://inspect.dev/changelog/inspect-can-now-debug-chrome-on-ios
