### ISSUE TITLE
Can't inspect pseudo element ::before

### ISSUE THREAD

**Issue by phil-lgr** [inspectdev/inspect-issues#26]
- inspect-app version: 0.5.66
- OS ARCH VERSION: darwin x64 19.6.0
- Electron: 11.2.1
- Language: undefined

Look like I can't inspect ::before pseudo element

![image](https://user-images.githubusercontent.com/9644867/110546032-f6299900-80fb-11eb-9f83-87e7b177689b.png)

**Comment by auchenberg** [comment]
@phil-lgr Thanks for reporting this! Will be fixed in `v0.6.3` shipping tonight!
