### ISSUE TITLE
No targets found on Windows 10

### ISSUE THREAD

**Issue by mtsknn** [inspectdev/inspect-issues#30]
- inspect-app version: 0.5.66
- OS ARCH VERSION: win32 x64 10.0.19041
- Electron: 11.2.1
- Language: undefined

Also:

- iPad Mini 5 (iPadOS 14.4)
- Windows 10

Steps to Reproduce:

1. Open iTunes
2. Connect iPad to laptop using cable
3. Sync in iTunes
4. Open Safari on iPad
5. Open a website in Safari
6. Open Inspect
7. Inspect does recognize my iPad, but under its name on the left, it says "No targets found" :(

I have seen #5, but I'm already doing what's suggested there (open Inspect *after* pairing device with iTunes).

Any ideas what I could try?

**Comment by auchenberg** [comment]
@mtsknn Have you enabled Web inspector on your iPad per https://webkit.org/web-inspector/enabling-web-inspector/#ios-device?

**Comment by natannovum** [comment]
I have the same problem on:
- iOS 14.4 
- MacOS Catalina 10.15.7 (19H15)

Mobile Safari Web Inspector enabled.

Please advise.

<img width="1792" alt="Screenshot 2021-03-22 at 17 23 31" src="https://user-images.githubusercontent.com/1637907/112032032-dfd80000-8b33-11eb-8fc9-a495f8bf4dc8.png">

**Comment by FrancescRRSapa** [comment]
Having the same issue on iPhone 7, ios version 14.4.1, trying to get it working on Windows

**Comment by auchenberg** [comment]
@natannikolic Do you have Safari running on your mac? If so try to close Safari before opening Inspect.

**Comment by auchenberg** [comment]
@FrancescRRSapa Have you enabled Web Inspector on your iOS device?

**Comment by FrancescRRSapa** [comment]
Hello, sorry for late answer. I got the solution by opening iTunes on Windows. I understood that by having iTunes installed was enough but I had to open it to see the targets. Thanks for the answer.

**Comment by DavGarcia** [comment]
I was having the same issue, auchenbeg's comment about Enabling Web Inspector worked for me! Can someone on the inspect team add that step to the Download page? https://inspect.dev/download That would be super helpful.

**Comment by auchenberg** [comment]
@DavGarcia Good feedback! This will be addressed in https://github.com/inspectdev/inspect-issues/issues/11

**Comment by mtsknn** [comment]
@auchenberg I procrastinated on this until the ~last day of my free trial, but the app says that my trial has already expired, so I can't test whether enabling Web Inspector on my iPad solves the problem. 😄

If enabling Web Inspector is required, I very much agree that it should be documented somewhere. #11 has been closed, but I can't see anything related to enabling Web Inspector at https://inspect.dev/download or on any other pages at inspect.dev?

Another thing that you might want to check is the "Your Inspect trial ends soon" emails. My such email said that my trial ends on "April 15, 2021 at 11:46:27 AM UTC," but the trial has already expired (I can't use the app anymore), even though it's still April 14th (see https://time.is/UTC).

**Comment by auchenberg** [comment]
@mtsknn I'd be happy to extend your trial if you wanna use Inspect a little more. Which email did you use?

Inspect now has an in-app guide that takes you through the same needed to get things working on Windows and Mac, so the instructions have been removed from `/downloads`.

I will give the emails a look. This sounds like a timezone issue. Thank you!
