### ISSUE TITLE
Capacitor webview nesting output

### ISSUE THREAD

**Issue by alexcroox** [inspectdev/inspect-issues#31]
Console output from [Capacitor](https://capacitorjs.com/) webviews seems to be nested, meaning I need to continuously expand the tree to see normal console.log() outputs.

inspect.dev:

![image](https://user-images.githubusercontent.com/1065835/111496014-cef44c80-8737-11eb-87e4-7157fbd7bdb1.png)

Safari:

![image](https://user-images.githubusercontent.com/1065835/111496080-e03d5900-8737-11eb-9fbc-6e7f955516e3.png)

**Comment by auchenberg** [comment]
@alexcroox Very interesting. Would you happen to know a great Capacitor demo project or something that reproduces this?

**Comment by alexcroox** [comment]
My free trial has expired so I'm unable to reproduce it now sorry

**Comment by auchenberg** [comment]
@alexcroox Please let me know your account email, then I can give you a subscription as a thank you for your help

**Comment by auchenberg** [comment]
@alexcroox Fixed in master. Lands in next build.

**Comment by alexcroox** [comment]
I can confirm this is now fixed, thank you!
