### ISSUE TITLE
Add Linux support

### ISSUE THREAD

**Issue by subjectdenied** [inspectdev/inspect-issues#33]
shouldn't electron allow this anyways?

also the source-files don't exclude anything other than a readme file?

**Comment by subjectdenied** [comment]
for anyone finding this issue of interest - there is a solution to use inspect.dev on linux from within a virtualmachine in virtualbox
- install latest virtualbox
- get a windows 10 vm (those test-images microsoft publishes should work), extract the zip-file, import the resulting .ova ("import virtual appliance")
- config your vm to use usb3 (xhci)
- not sure about this, but i set the usb-device filter to my iphone connection too (so device-is-plugedin events go directly into the vm)
- install latest itunes for windows
- make sure your vm is authorized with your ios device, and your ios device shows up in itunes (may take a while)
- start inspect.dev
- happy debugging
- extra info: in case your web-page uses websockets, make sure to tunnel the connection through ngrok or similar (as self signed certificates are not possible with websockets on ios)

**Comment by auchenberg** [comment]
Linux is currently not supported as https://libimobiledevice.org hasn't been validated together with Inspect. We might be able to provide builds, but https://libimobiledevice.org would have to be installed manually on the user's machine prior to Inspect.

@subjectdenied I'd be happy to try to make an experimental build for you if you are up for trying things? Are you on Ubuntu?

**Comment by subjectdenied** [comment]
no, on fedora, but i usually can get stuff working on fedora that is meant for ubuntu, and afaik libmobiledevice is available on fedora too

thanks btw for looking into this, very much appreciated!

**Comment by auchenberg** [comment]
Alrighty. Linux builds will be generated from next release. Let's try this.

**Comment by auchenberg** [comment]
@subjectdenied Try to grab the latest builds from https://github.com/inspectdev/inspect-release/releases/tag/v0.6.6 and see what works for you. You probably need to install and start https://libimobiledevice.org/ before opening Inspect.

**Comment by subjectdenied** [comment]
thank you very much for providing linux builds!

i tried the rpm-build. after starting the usbmuxd-service i got rid of an error message (/var/usbmuxd not existing or not readable), however i can't get the login-flow working. i'm using firefox as my default browser, if starting inspect-app without superuser-rights, clicking the login-button, does nothing and console tells me, that there is no action linked to the click. using superuser rights (and the no-sandbox flag) clicking the login-button opens the gnome-webbrowser (epiphany), login in at the webpage works, however the state doesnt change in the app. i will try to set my default browser to chrome, and see if it makes a difference

**Comment by subjectdenied** [comment]
changing my default browser to chrome didn't work, at least not as user

this is the error i get when clicking the login-button:

client:execCommand.result undefined
client:execCommand inspect:openLogin

i also tried the appimage, same behaviour

**Comment by auchenberg** [comment]
@subjectdenied Thanks for testing things! I think I found and fixed the issue. Try to grab the latest release `v0.6.8`. I just validated myself with a fresh Ubuntu install:

<img width="1336" alt="Screen Shot 2021-05-10 at 10 55 39 PM" src="https://user-images.githubusercontent.com/173559/117765557-ff5de180-b1e2-11eb-88e0-bf4c3682a11c.png">

<img width="1336" alt="Screen Shot 2021-05-10 at 10 55 51 PM" src="https://user-images.githubusercontent.com/173559/117765549-fc62f100-b1e2-11eb-98f8-be29d7cfb579.png">

**Comment by piec** [comment]
It's working for me too, version 0.6.9 on Arch Linux
I've had to open Inspect with the `inspect://login?...` url manually, probably due to my setup

**Comment by auchenberg** [comment]
@piec Great! Can you try to install https://libimobiledevice.org/#get-started on your machine, and start `libimobiledevice` prior to launching Inspect, and see if Inspect can find any of your devices?

**Comment by piec** [comment]
@auchenberg Hi, I already have libimobiledevice installed (git).
I can run `idevicesyslog` and Inspect concurrently.

I made a [basic AUR package](https://aur.archlinux.org/packages/inspect/) (user contributed packages) for Arch based on the .deb

**Comment by auchenberg** [comment]
@piec Fantastic, so we have Linux builds working?

**Comment by piec** [comment]
Not sure I understand the question :)
This Arch Linux package is a repackaging of the .deb provided in the [Inspect releases](https://github.com/inspectdev/inspect-release/releases) to the Arch Linux package format. And it works for me

**Comment by auchenberg** [comment]
@piec I was asking to confirm that Inspect works using the `deb` package using libimobiledevice, which it sounds like it does, right? I'm not a Linux user myself, so I was shooting in the blind here when making this build.

**Comment by piec** [comment]
Yes, Inspect uses my system's usbmuxd / libimobiledevice

**Comment by auchenberg** [comment]
Closing as this shipped in `v0.7.0`
