### ISSUE TITLE
Cache issue with webpack:// keeping the old value

### ISSUE THREAD

**Issue by chrisribe** [inspectdev/inspect-issues#34]
- inspect-app version: 0.6.1
- OS ARCH VERSION: win32 x64 10.0.18363
- Electron: 11.2.1
- Language: undefined

Steps to Reproduce:

1. Webpack file with .map
2. Update build and redeploy
3. Clear safari cache
4. Reload, inspect still shows old webpack but new source packed file is present.

**Comment by auchenberg** [comment]
@chrisribe Thanks for the report! Can you share a demo project, or the specific webpack configuration? This works as expected in regular Chrome?

**Comment by auchenberg** [comment]
This may be caused by https://github.com/inspectdev/inspect-issues/issues/36

**Comment by chrisribe** [comment]
Sorry missed your comment, no I cannot. I will retest this when I get a chance.
