### ISSUE TITLE
Spinner overlays are added multiple times if there's an error when fetching an element style

### ISSUE THREAD

**Issue by yannbf** [inspectdev/inspect-issues#38]
As can be seen in the gif:
![2021-03-29 at 19 51 42 - Blush Blackbird](https://user-images.githubusercontent.com/1671563/112878701-88eca080-90c8-11eb-8390-e1edbc31c366.gif)

- inspect-app version: 0.6.3
- OS ARCH VERSION: darwin x64 19.6.0
- Electron: 11.2.1
- Language: English

The main problem of course is the error that occurs so I don't have access to the styles from the elements, but I noticed that the overlay keeps getting added even though there's already one there.

In regards to the issue, closing safari and opening again, then reconnecting with inspect, fixed it.

Steps to Reproduce:

1. I'm running a React app, testing it wirelessly on Safari. 

The error that occurred looks like:
```js
InspectorBackend.js:53 Protocol Error: the message with wrong id: {
  result: {
    inlineStyle: {
      cssProperties: [],
      shorthandEntries: [],
      styleId: { styleSheetId: '11', ordinal: 0 },
      width: '',
      height: '',
      range: { startLine: 1, startColumn: 0, endLine: 1, endColumn: 0 },
      cssText: '',
    },
  },
  id: 10067,
}
```

**Comment by auchenberg** [comment]
This is caused by https://github.com/inspectdev/inspect-issues/issues/29. You can see that out in the console to the right. The connection to the get device gets messed up.

**Comment by auchenberg** [comment]
Thanks for reporting @yannbf !
