### ISSUE TITLE
Debugger panel scrolls to bottom every time a call stack is selected

### ISSUE THREAD

**Issue by yannbf** [inspectdev/inspect-issues#39]
When debugging the app, it's very common to jump around from stack to stack. It's not too big of a deal, but the fact that the panel scrolls down every time I select it can become a bit annoying.

![2021-03-29 at 20 04 24 - Plum Nightingale](https://user-images.githubusercontent.com/1671563/112880054-41671400-90ca-11eb-97fd-3cc5d18c412a.gif)

- inspect-app version: 0.6.3
- OS ARCH VERSION: darwin x64 19.6.0
- Electron: 11.2.1
- Language: English (btw this was filled as `undefined` from the Feedback button, I had to write English myself)

Steps to Reproduce:

1. Create a dynamic breakpoint and reach it
2. In the call stack column, jump from one stack to the other

**Comment by auchenberg** [comment]
Thanks for reporting this @yannbf. This is a feature of Chrome DevTools itself, and is therefore upstream, so won't be fixing.
