### ISSUE TITLE
Add shortcut to clear cache. 

### ISSUE THREAD

**Issue by auchenberg-stripe** [inspectdev/inspect-issues#4]
" I wanted to ask one thing... Is it possible to add a way (preferably w/ a configurable keyboard shortcut) to nuke the browser cache on the connected iOS / Android device?  That is one of my larger pain points when trying to debug on mobile browsers."

Source: https://twitter.com/ffaubert

**Comment by ffaubert** [comment]
What I usually struggle with here is connecting mobile safari to Web Inspector, and despite my attempts to empty the cache through Web Inspector or force a hard reload often times I get back cached assets and have to go through a time consuming step of either wiping all cache data on the device directly, or rebuilding the server side of my application with a different cache busting value.  For all other (desktop) browsers I have a keybind to nuke the cache, and then reloading always fetches the updated files as I am developing.  It would be ideal if there was a menu option to clear the cache on the connected device.  I can use the macOS keyboard settings to override the keyboard shortcut - that part is likely not worth dev time.

I will say that I sent you this request before noticing that there is a force reload option.  That may very well be good enough if it works.  I'm not actively developing any mobile facing features at the moment to get a true test, but if that works well then a separate action just to clear the cache is just a nice-to-have and not super important.

Thank you so much for the consideration!  Inspect is such a great addition to my toolkit.  Thank you for making this!

**Comment by auchenberg** [comment]
@ffaubert I've now mapped the functionality, so you can open DevTools -> Network -> Disable Cache on network requests, and if you do a Command+Option+R on Mac or Control+Shift+R on Windows or Linux from Elements you'll make a Page.reload with an ignored cache. 

This is standard in Chrome DevTools, and now works with Safari.

![](https://i.stack.imgur.com/Grwsc.png)

Safari Inspector actually supports this via this little icon too:

![](https://i.stack.imgur.com/9xpqb.png)
