### ISSUE TITLE
Search does not work after refreshing the connected app

### ISSUE THREAD

**Issue by yannbf** [inspectdev/inspect-issues#40]
When debugging, I use the search feature a lot. I noticed that it currently behaves inconsistently.

Sometimes it finds results instantly, sometimes it hangs in the loading state... but if I press enter again, it works right away. 

When it works, if you click on the app indicator:

![image](https://user-images.githubusercontent.com/1671563/112881977-a7ed3180-90cc-11eb-993c-ae49269b5250.png)

For some reason everything reloads. When it does, when doing the search again, it yields no results:

![2021-03-29 at 20 19 20 - Tan Reptile](https://user-images.githubusercontent.com/1671563/112881648-3c0ac900-90cc-11eb-9331-5baa438d283f.gif)

What I'm wondering is if the behavior of clicking in the app indicator(while it's already selected) refreshing everything is intended. 
As a result, you might lose the state of what you were doing before. Maybe for better UX, it should not do anything when clicking in the indicator if the app is already selected, and there could be a small refresh button by the side, which indeed would refresh the app.

- inspect-app version: 0.6.3
- OS ARCH VERSION: darwin x64 19.6.0
- Electron: 11.2.1
- Language: English

Steps to Reproduce:

1. Use the search tool with any code from your codebase, see the results.
2. Click on the app you're connected, it will refresh it.
3. Try to use the search again. It will say there are no results.

**Comment by auchenberg** [comment]
@yannbf This should be resolved in `v0.6.5`
