### ISSUE TITLE
iPad not being recognized by Inspector

### ISSUE THREAD

**Issue by briandeng750** [inspectdev/inspect-issues#42]
- inspect-app version: 0.6.3
- OS ARCH VERSION: win32 x64 10.0.19042
- Electron: 11.2.1
- Language: undefined

Steps to Reproduce:

1. Enabled Web Inspector in iOS Safari settings (iOS v 14.4.2)
2. Connected iPad to my PC via USB
3. Launched Inspector

Available devices shows "No devices found"

Is there anything else I need to enable or do?

**Comment by briandeng750** [comment]
Installed iTunes and I see the iPad now, however I still see the "No targets found" message so I cannot inspect the loaded page.

**Comment by auchenberg** [comment]
@briandeng750 Which app are you trying to inspect? Safari? Did you restart Safari on your device after enabling web inspector?

**Comment by briandeng750** [comment]
@auchenberg I was able to get it to work (Safari) by adding the URL to my home screen. Not sure if that was just a coincidence or not. I had restarted Safari several times (even restarted the iPad). But I think my issue is resolved now.
