### ISSUE TITLE
No targets found for my iPhone running iOS 14.3

### ISSUE THREAD

**Issue by hbinkle** [inspectdev/inspect-issues#45]
- inspect-app version: 0.6.3
- OS ARCH VERSION: win32 x64 10.0.19042
- Electron: 11.2.1
- Language: undefined

Steps to Reproduce:

1. The phone is listed
2. Safari is running, weblog is enabled

**Comment by auchenberg** [comment]
@hbinkle Have you followed the instructions on http://inspect.dev/download? You need to have started iTunes on your Windows machine to start the iOS driver.

**Comment by hbinkle** [comment]
@auchenberg,
thanks, that's it. iTunes was installed, but I haven't started it since my last reboot.
Maybe you can add a check for iTunes running in inspect?

**Comment by auchenberg** [comment]
@hbinkle Good feedback. This will be added in the next update.
