### ISSUE TITLE
Support zoom in/out

### ISSUE THREAD

**Issue by aparajita** [inspectdev/inspect-issues#47]
- inspect-app version: 0.6.3
- OS ARCH VERSION: darwin x64 20.3.0
- Electron: 11.2.1
- Language: undefined

It would be lovely if you could support zoom in/out (as devtools does in the browser) for us old folks whose eyesight is not so great after 36 years of staring at code.  😁

Cmd/Ctrl-Plus zoom in
Cmd/Ctrl-Minus zoom out

**Comment by auchenberg-stripe** [comment]
@aparajita Would you like to zoom all of Inspect, or just the DevTools?

**Comment by aparajita** [comment]
Good question. I guess you might as well zoom the whole thing, the sidebar text is pretty small.

**Comment by auchenberg** [comment]
@aparajita Alright. Landed in master. Will ship in next build.
