### ISSUE TITLE
Remember Window Size and Position

### ISSUE THREAD

**Issue by samholmes** [inspectdev/inspect-issues#50]
- inspect-app version: 0.6.3
- OS ARCH VERSION: darwin x64 20.3.0
- Electron: 11.2.1
- Language: undefined

Steps to Reproduce:

1. Open App
2. Resize and Position Window
3. Close App
4. Reopen App

Expected:

Window size and position remains the same as before closing the app.

Results:

Window size and position returns to default size and centered.

**Comment by auchenberg** [comment]
@samholmes Thanks for reporting. Will be fixed in new update!
