### ISSUE TITLE
No Targets Found

### ISSUE THREAD

**Issue by richardshergold** [inspectdev/inspect-issues#54]
When I open Inspect I see my device listed but below that it says "No Targets Found" - I can debug the app (an Ionic app) fine through Xcode but not in Inspect?

**Comment by richardshergold** [comment]
I think it was down to the app signing

**Comment by auchenberg** [comment]
@richardshergold Did you solve this?

**Comment by richardshergold** [comment]
Yes I think the app signing was the issue
