### ISSUE TITLE
Recording failed 'Tracing' domain was not found

### ISSUE THREAD

**Issue by simonmulser** [inspectdev/inspect-issues#55]
- Inspect version: 0.6.5
- Electron: 11.2.1
- OS version and architecture: darwin x64 19.6.0
- Language: undefined

Steps to Reproduce:

1. Connect iPad via USB to MacBook
2. Open Safari on iPad and Open page google.com
3. Start Inspect
4. Select Google from side bar
5. Select Perfomance tab
6. Start record

<img width="1036" alt="image" src="https://user-images.githubusercontent.com/2686617/114901613-41c71500-9e15-11eb-8e35-165d83563ca2.png">

**Comment by auchenberg** [comment]
Thanks for reporting this @simonmulser. Performance tools aren't supported at the moment. Will be disabled in the UI soon. Tracked in https://github.com/inspectdev/inspect-issues/issues/49
