### ISSUE TITLE
iPhone apps not showing on PC's Inspect

### ISSUE THREAD

**Issue by SamanthaKraft** [inspectdev/inspect-issues#57]
- Inspect version: 0.6.5
- Electron: 11.2.1
- OS version and architecture: win32 x64 10.0.19042
- Language: undefined

Steps to Reproduce:

1. Use window 10 PC to inspect cordova web app (UIWebView) on iphone
2. itunes is running and synced, inspect is also running
3. App shows up on phone but does not show up under target iPhone's section
4. Tested other web apps with the same results (ionic built and UIWebView)

**Comment by auchenberg** [comment]
@SamanthaKraft Is your app running in development mode? If the app has been published to the App Store or Testflight, Apple disables the debugging capabilities for the particular web view.

Do normal Safari tabs show up for your device?

**Comment by SamanthaKraft** [comment]
Oh gotcha, that makes sense. Thank you.
Yeah apps I was testing had been published to the App Store and downloaded to the phone. 
Normal Safari browser does work and debugs as expected. 
So just to confirm, I'll need to run the app in dev mode, correct?

**Comment by auchenberg** [comment]
@SamanthaKraft Yup, that is correct. See https://webkit.org/web-inspector/enabling-web-inspector/ for more details on which targets you can debug.
