### ISSUE TITLE
Add support for different breakpoint types

### ISSUE THREAD

**Issue by samholmes** [inspectdev/inspect-issues#61]
This is a feature request to add support for all of DevTool's breakpoint types: conditional breakpoint and logpoint. Currently, secondary clicking on a line number does nothing; I'd expect it to show options for the breakpoint type.

**Comment by auchenberg** [comment]
This should be handled as soon as context menu lands, https://github.com/inspectdev/inspect-issues/issues/53

**Comment by auchenberg** [comment]
Landed in next release.

**Comment by samholmes** [comment]
I am still not seeing this feature. I'm on macOS.

<img width="255" alt="Screen Shot 2021-10-25 at 12 40 30" src="https://user-images.githubusercontent.com/517469/138759480-b2bad47c-c3dd-4eaa-8834-b19ba1b370b9.png">

<img width="577" alt="Screen Shot 2021-10-25 at 12 40 49" src="https://user-images.githubusercontent.com/517469/138759568-a29c0187-bd38-4eb9-9fed-0baad88c753e.png">

**Comment by auchenberg** [comment]
@samholmes Should be supported in the latest version. If you have a minified script you need to pretty print first.

<img width="282" alt="Screen Shot 2021-10-26 at 9 08 36 AM" src="https://user-images.githubusercontent.com/173559/138896160-6f9d7cbd-aebe-43ba-9281-b895d13e8003.png">

What kind of script are you debugging? Anything sourcemapped?

**Comment by samholmes** [comment]
@auchenberg Yes the script I'm debugging is sourcemapped. I'm debugging webpack output that has sourcemaps (`devtool: 'cheap-source-map',` in my webpack config). Why does sourcemapping affect the ability to set breakpoints in both the mapped version and the unmapped version (Only 'Add breakpoint' is a context menu option in the unmapped source code, and choosing it always opens a source mapped version of the file).
