### ISSUE TITLE
Debugger: Callstack, variable scopes and hovers are blank when hitting a breakpoint

### ISSUE THREAD

**Issue by samholmes** [inspectdev/inspect-issues#62]
- Inspect version: 0.6.7
- Electron: 11.2.1
- OS version and architecture: darwin x64 20.3.0
- Language: undefined

Steps to reproduce:

1. Open the debugger on a connected device
2. Open Source tab
3. Set a breakpoint
4. Wait for breakpoint to be reached

What happens:

Call stack is blank.

<img width="216" alt="Screen Shot 2021-05-04 at 5 20 07 PM" src="https://user-images.githubusercontent.com/517469/117084852-1c834380-acfd-11eb-9d5c-ccaefb3471c8.png">

Hovering over state show no information.

<img width="335" alt="Screen Shot 2021-05-04 at 5 23 34 PM" src="https://user-images.githubusercontent.com/517469/117085033-94516e00-acfd-11eb-9012-91e4464d6e03.png">

Even the console doesn't print information.

<img width="848" alt="Screen Shot 2021-05-04 at 5 30 38 PM" src="https://user-images.githubusercontent.com/517469/117085392-78020100-acfe-11eb-9619-3e5b2e46c3c0.png">

I apologize for the brevity here. Some more information:

* Inspecting a connected iPhone X device.
* I'm inspecting a web view in an app which is loading an HTML file from a `file:///` location.

**Comment by auchenberg** [comment]
@samholmes Thanks for the report Sam! So to understand this correctly you are:
1. Able to set breakpoints
2. Hit that breakpoint
3. But the variable scopes and hovers aren't working + the console isn't in the right context?

Q: Are the callstack available?

**Comment by samholmes** [comment]
Correct about all three points.

As shown in OP, the call stacks aren’t available either.

**Comment by auchenberg** [comment]
@samholmes Alrighty. Looks like some mapping between Webkit and Chrome isn't working as expected.

**Comment by auchenberg** [comment]
@samholmes I can't reproduce this. Can you elaborate more about the codebase? How is the app built? TypeScript?

**Comment by samholmes** [comment]
Seems to be fixed as of version 0.7.2
