### ISSUE TITLE
Inspect sometimes does not pick up PWA instances

### ISSUE THREAD

**Issue by yannbf** [inspectdev/inspect-issues#63]
- Inspect version: 0.6.7
- Electron: 11.2.1
- OS version and architecture: darwin x64 19.6.0
- Language: undefined

Sometimes (maybe 40% of the times?), inspect doesn't pick up the connection when I open my PWA. Also, when it does pick up the connection and I force close the app, it's not cleaned up, and if I refresh inspect, it still doesn't detect that there's no connection anymore.

Steps to Reproduce:

Follow the video:
https://streamable.com/ph95xg

**Comment by auchenberg** [comment]
@yannbf Thanks for the report! Inspect queries for devices and pages every 5th second, so you won't be able to see pages and apps instantly appear or disspear. What happens if you lets say wait 10sec?

**Comment by yannbf** [comment]
Hey @auchenberg, I reproduced this scenario and let inspect open for a minute. Nothing happened. Tried putting the app in background then bringing it back, still nothing. 

After that, I force closed the app and opened again, and it was picked up instantly. Give it a [try yourself](http://vacinados.netlify.app), maybe it helps!

**Comment by auchenberg** [comment]
@yannbf Alrighty, thanks for the example link. I will try to reproduce.

**Comment by auchenberg** [comment]
This will be fixed in the next release. Thanks for reporting @yannbf !
