### ISSUE TITLE
Setup window size / viewport doesn't scroll and doesn't fit content

### ISSUE THREAD

**Issue by benjibee** [inspectdev/inspect-issues#65]
- Inspect version: 0.6.8
- Electron: 12.0.7
- OS version and architecture: darwin arm64 20.4.0
- Language: undefined
- Computer model: MacBook Air (M1, 2020)
- Screen resolution: 13,3-inch (2560 × 1600)

Steps to Reproduce:

1. Download and open application (on 13.3" screen)
2. Attempt to click "Continue" button or scroll vertically on 1st or 3rd screen

<img width="1062" alt="image" src="https://user-images.githubusercontent.com/620119/118113545-bb3b2e80-b3e6-11eb-83e4-56b39fe1708f.png">

**Comment by auchenberg** [comment]
@benjibee Thanks for the report. That will get fixed in the next release.
