### ISSUE TITLE
Unable to purchase subscription...?

### ISSUE THREAD

**Issue by LeapFrogCodeDesign** [inspectdev/inspect-issues#66]
- Inspect version: 0.6.8
- Electron: 12.0.7
- OS version and architecture: win32 x64 10.0.19042
- Language: undefined

Steps to Reproduce:

1. Logged on, bought a subscription
2. It shows me as having an expiring subscription
3. Download latest, install
4. It tells me my subscription has expired
5. Technically, I did this twice.  Hopefully I won't pay $198 and STILL not be able to download

**Comment by auchenberg** [comment]
We resolved this over Intercom.
