### ISSUE TITLE
Reconnection to the same device quite often fails

### ISSUE THREAD

**Issue by derwaldgeist** [inspectdev/inspect-issues#67]
- Inspect version: 0.6.8
- Electron: 12.0.7
- OS version and architecture: darwin x64 20.5.0
- Language: undefined

First off, I love this app and definitely plan to use it. Having some problems with my iPhone 12 Pro Max, though. It connects fine on first startup of the app, but if I switch to another app and try to go back, quite often I only see empty Elements tab.

Steps to Reproduce:

1. Open Inspect
2. Inspect an iPhone 12 Pro Max connected via Lightning
3. Switch to an iPhone X
4. Switch back to the iPhone 12 Pro Max

BTW: I am writing this while the Safari web inspector is completely broken after updating macOS to Big Sur 11.4. Maybe that's a side-effect. That bug in Safari brought me to Inspect, as someone promoted your app in the Apple forums. So that's good for your team :-)

**Comment by derwaldgeist** [comment]
Update: Sometimes I can only see a fragment of the actual page:

![image](https://user-images.githubusercontent.com/3984535/119698493-949ede00-be51-11eb-9743-075270b16df2.png)

As you can see, head and body contents are missing, although the page is being displayed correctly on the device.

**Comment by auchenberg** [comment]
@derwaldgeist Thanks for reporting this, and giving Inspect a spin. Currently installing iOS 14.6 to try to reproduce this.

**Comment by auchenberg** [comment]
@derwaldgeist This should be fixed in the next build available.
