### ISSUE TITLE
Can't edit the remote device's CSS properties via the app, as they are read-only

### ISSUE THREAD

**Issue by shaya-tabit** [inspectdev/inspect-issues#7]
- inspect-app version: 0.5.61
- OS ARCH VERSION: win32 x64 10.0.19042
- Electron: 11.2.1
- Language: undefined

Steps to Reproduce:

1. On Windows 10, open iTunes and connect an iPad 5 via USB to the PC
2. Open "Safari" on the iPad.
2. Open "inspect.dev" app on Windows, and connect successfully to the iPad.
3. On inspectdev, all the CSS properties are in "_italics_" font and are **read-only** (I can however add a "style" HTML attribute with rules to any of the remote page elements, and it will reflect at the iPad).

**Comment by auchenberg** [comment]
@shaya-tabit Which iOS version and device are you on?

**Comment by shaya-tabit** [comment]
@auchenberg - my bad, forgot to mention:

* iOS 14.4
* iPad Mini 5

![EvZlLpRXcAYPccD](https://user-images.githubusercontent.com/72202898/109768731-f6a8c800-7c01-11eb-82cb-3ff9374d2110.png)

**Comment by NielsLeenheer** [comment]
I'm running into the same problem with iOS 14 devices running in the Simulator. CSS is read only, shown in italic and cannot be edited.

<img width="1629" alt="" src="https://user-images.githubusercontent.com/233230/109973170-5aadb800-7cf8-11eb-9988-56166b2d27e8.png">

**Comment by auchenberg** [comment]
Should be fixed in next update!
