### ISSUE TITLE
Network tab stops showing requests

### ISSUE THREAD

**Issue by glittle** [inspectdev/inspect-issues#74]
- Inspect version: 0.6.9
- Electron: 13.1.1
- OS version and architecture: win32 x64 10.0.19042
- Language: undefined

The network tab correctly shows requests for a while.  Then it stops updating after a few pages.

Steps to Reproduce:

1. Connect iPhone to Windows computer
2. Run Inspect
3. Watch network tab

Haven't pinpointed an exact cause or been able to replicate it the same way each time.

**Comment by auchenberg** [comment]
Inspect `0.6.9` has a range of smaller issues with the data powering the network tool. This should be resolved in the next release. Please try things out, and see if it's still broken for you. Hopefully we got it.
