### ISSUE TITLE
Network: Preserve log not working

### ISSUE THREAD

**Issue by glittle** [inspectdev/inspect-issues#75]
- Inspect version: 0.6.9
- Electron: 13.1.1
- OS version and architecture: win32 x64 10.0.19042
- Language: undefined

Steps to Reproduce:

1. Connect to iPhone
2. In the Inspect devtools view, network tab, turn on "Preserve log"
3. Navigate between pages in iPhone on Safari

The network log should not reset/clear between pages, but it is doing so.

**Comment by auchenberg** [comment]
Notes: Validated

**Comment by auchenberg** [comment]
This will be fixed in next minor release.
