### ISSUE TITLE
Support for amd64 architecture

### ISSUE THREAD

**Issue by uschmann** [inspectdev/inspect-issues#76]
Hi 
i am trying to install inspect on my ubuntu amd64 machine.

If i run this:

```bash
sudo dpkg -i Inspect-0.7.0-linux-arm64.deb
```

I get this error message:

```bash
dpkg: error processing archive Inspect-0.7.0-linux-arm64.deb (--install):
 package architecture (arm64) does not match system (amd64)
Errors were encountered while processing:
 Inspect-0.7.0-linux-arm64.deb
```

Where can i get the am64 version? Or is this not supported?

Thanks in advance

**Comment by auchenberg** [comment]
You should be able to grab the correct deb for your platform on https://github.com/inspectdev/inspect-release/releases/tag/v0.7.0

**Comment by auchenberg** [comment]
Updated link on /downloads to GitHub releases to clarify what builds that are available.
