### ISSUE TITLE
Core: No devices found on MacOS when xcrun simctl isn't installed.

### ISSUE THREAD

**Issue by bclin087** [inspectdev/inspect-issues#77]
- Inspect version: 0.7.2
- Electron: 13.1.1
- OS version and architecture: darwin x64 20.5.0
- Language: undefined

Steps to Reproduce:

1. Run setup, iPad paired in Finder, trust this computer, etc... all done.
2. No devices found in Inspect window.

**Comment by auchenberg** [comment]
@bclin087 What kind of app are you trying to debug on your iOS device? If you are running Safari at the same time, you might want to close Safari prior to opening Inspect on your Mac, as they can fight for the device connection

**Comment by uncasually** [comment]
I have this same issue trying to debug Safari on iOS 14.6. Followed all instructions, even installed libimobiledevice after iTunes connect didn't work.

- iOS 14.6
- Inspect 0.7.2
- MacOS 10.14.6

**Comment by auchenberg** [comment]
@uncasually Alright. Let's try to debug this. 

For MacOS 10.14.6, do you see your IOS device in `Finder` or do you have to open iTunes? 
Have you granted permission on your iOS device for your mac to access the device?
Does the iOS device show up in Inspect, or is it all empty?
Given you are on MacOS, do remote debugging with desktop Safari work?
Have you restarted your IOS device after enabling web inspector?

**Comment by bclin087** [comment]
> @bclin087 What kind of app are you trying to debug on your iOS device?

Web app, opened in mobile Safari and Chrome (tried on both separately)

> If you are running Safari at the same time, you might want to close Safari prior to opening Inspect on your Mac, as they can fight for the device connection

Just tried again with Safari closed, still no luck.

**Comment by auchenberg** [comment]
@bclin087 Alright, thank you. Can I try to get you to download Inspect v.0.6.9 and see if this fixes the problem? There shouldn't be any changes between the versions but let's try to eliminate that. https://github.com/inspectdev/inspect-release/releases/tag/v0.6.9

**Comment by auchenberg** [comment]
The issue seems to happen with iOS 14x versions on MacOS versions. One user has had success in downgrading to https://github.com/inspectdev/inspect-release/releases/tag/v0.6.9 which made the device discoverable. It would be great if you could help try this out @bclin087  @uncasually

**Comment by auchenberg** [comment]
@bclin087 @uncasually The issue has been identified and fixed. Caused by `xcrun` provided by Xcode Commandline Tools isn't installed on the machine. Will be fixed in `v0.7.3` shipped in a bit. Please install and validate
