### ISSUE TITLE
Support screencasting for IOS devices

### ISSUE THREAD

**Issue by auchenberg-stripe** [inspectdev/inspect-issues#8]
Inspect should support screencasting for IOS devices,

![](https://umaar.com/assets/images/dev-tips/screencasting.gif)

https://developers.google.com/web/tools/chrome-devtools/remote-debugging

**Comment by AndreyTepaykin** [comment]
Yes that would be great!

**Comment by auchenberg** [comment]
Research notes: Maybe use https://github.com/lovell/sharp to resize the images coming from webkit in memory, and then return to the client based on the max dimensions.

**Comment by auchenberg** [comment]
Experimental screencasting landed in `v0.6.9`. https://inspect.dev/changelog
