### ISSUE TITLE
Cordova webviews aren't detected

### ISSUE THREAD

**Issue by auchenberg-stripe** [inspectdev/inspect-issues#9]
> And one more. It doesn't detect cordova apps.

Reported by Andrey Tepaykin

**Comment by AndreyTepaykin** [comment]
I used released package, not development.
Tested with development package and it works fine.
Sorry my mistake.

**Comment by BeatriceThalo** [comment]
This tool is just the thing I was looking for!
My cordova webapp shows in Inspect's list, and hovering over the file:// list item shows the light blue highlight on my iPhone's screen, but no Element tree appears.
![inspect cordova webapp](https://user-images.githubusercontent.com/17069266/109878325-237ccf80-7c42-11eb-90e3-c90b6157fd20.jpg)

**Comment by BeatriceThalo** [comment]
I verified that I had a development build by inspecting the app through Safari on Mac Catalina, 

![DesktopSafari Elements](https://user-images.githubusercontent.com/17069266/109975490-ad6f7b80-7cc8-11eb-9912-163d3dd6c31c.png)

![DesktopSafari Console](https://user-images.githubusercontent.com/17069266/109975508-b2342f80-7cc8-11eb-84cb-6b8980adba94.png)

Also updated iTunes to Version 12.11.0.26, restarted my Win 10 PC, and still not showing any Elements in Inspect. Any tips?

Safari tabs on the iPhone do show in Inspect with their Element trees and the Console does generate an `alert("hello world")` onto the iPhone.

**Comment by auchenberg** [comment]
@BeatriceThalo Thanks for the report! What version of IOS and Cordova are you using?

**Comment by BeatriceThalo** [comment]
iOS 14.4, Cordova 9.0.0, cordova-ios 5.1.1

**Comment by auchenberg** [comment]
@BeatriceThalo Is Inspect completely dead for you, or is it just the Elements tab that doesn't work? Ex: Go to console, and write `alert('hi')` followed by enter.

**Comment by BeatriceThalo** [comment]
None of the tabs seem to load. Typing in the console and hitting enter makes the command disappear, rather than the history remaining on that pane with the expected undefined beneath it, and no popup shows on the iPhone. Sources, Applications > IndexedDB, are also empty. I could send a TestFairy link if that would help (adds your device's ID to provisioning of the .ipa).

**Comment by yannbf** [comment]
I can confirm that inspect managed to identify greatly an app I work with that uses `Cordova 9.0.0` and `cordova-ios 5.1.1`

**Comment by auchenberg** [comment]
@BeatriceThalo I think this may be caused by https://github.com/inspectdev/inspect-issues/issues/29. Can you try to restart Inspect a few times and see if it's able to connect to your webviews?
