### ISSUE TITLE
Can't install on Debian 11 Bullseye

### ISSUE THREAD

**Issue by gtbono** [inspectdev/inspect-issues#91]
I tried to install Inspect on Debian 11 Bullseye which was released yesterday and I couldn't.

As soon as I downloaded inspect-app 0.7.4, I tried to run the command:

`sudo dpkg -i Inspect-0.7.4-linux-amd64.deb ` 

But I couldn't install because I don't have libappindicator3-1

```
dpkg: dependency problems prevent configuration of inspect-app:
 inspect-app depends on libappindicator3-1; however:
  Package libappindicator3-1 is not installed.
```

And the problem is that this distro is new, but it doesn't have it on the package manager for me to install, apparently it only have 3-0.1 version (is this the correct package?)

```
$ apt-cache search libappindicator

libappindicator3-0.1-cil - CLI binding for libayatana-appindicator3 using GObject introspection
libappindicator3-0.1-cil-dev - CLI binding for libayatana-appindicator3 using GObject introspection
haskell-status-notifier-item-utils - StatusNotifierItem/libappindicator dbus implementation
libghc-status-notifier-item-dev - StatusNotifierItem/libappindicator dbus implementation
libghc-status-notifier-item-doc - StatusNotifierItem/libappindicator dbus implementation; documentation
libghc-status-notifier-item-prof - StatusNotifierItem/libappindicator dbus implementation; profiling libraries
```

I don't exactly know how to proceed here, I remember running in Ubuntu 18.04 and it was painless. Can I use this software on Debian?

**Comment by auchenberg** [comment]
This seems to be related to Electron. Other apps are broken https://github.com/RocketChat/Rocket.Chat.Electron/issues/1975 due to https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=895037

I'm no expert here, but I would expect this be solved by Electron.

**Comment by auchenberg** [comment]
@gtbono Please try to use the latest build where Electron has been upgraded.
