### ISSUE TITLE
Network:Size transferred over network is always the same as resource size (Network tab)

### ISSUE THREAD

**Issue by ShaCP** [inspectdev/inspect-issues#94]
- Inspect version: 0.7.4
- Electron: 13.1.1
- OS version and architecture: win32 x64 10.0.19043
- Language: undefined

In the network tab, if you hover over a response's size, you can see how much data was transferred over the network and how big is the resource. For example:
![network response](https://user-images.githubusercontent.com/47069245/134784109-3957317d-5124-4c2c-b546-cf0f1f7f7bff.png)

Using inspectdev, the two values are always the same. If it's, for example, a gzipped response, they shouldn't be the same.

**Comment by auchenberg** [comment]
Notes: Validated.
