### ISSUE TITLE
Device is connected and detected, but nothing happens

### ISSUE THREAD

**Issue by bsana1** [inspectdev/inspect-issues#95]
- Inspect version: 0.7.4
- Electron: 13.1.1
- OS version and architecture: win32 x64 10.0.19043
- Language: undefined

Steps to Reproduce:

1. Install inspect
2. Install iTunes
3. Connect iPhone, let it sync with iTunes
4. Open inspect and follow the wizard. 

Inspect shows the device on the left menu, but nothing happens. 

![image](https://user-images.githubusercontent.com/6021245/135486704-0530e904-3389-4874-95e4-40cfdfe520ac.png)

**Comment by auchenberg** [comment]
Hi @bsana1  👋 

Sometimes Inspect can have trouble finding the Safari tabs on your iOS device. 

The following steps unblock 80% of our users:
- Did you restart your iOS device after enabling Web Inspector?
- What kind of app are you trying to debug? Safari?
- If you are using Windows, did you install and start iTunes to make sure your iOS device is paired with your computer? Emphasis here is keep iTunes running to make sure the Apple driver is running in the backgorund.
- Make sure your iPhone is unlocked.
- Make sure Safari or the app you are trying to debug is the active one

Lets try to get to the bottom of this.

**Comment by bonniemurray** [comment]
@auchenberg I was having this issue and I tried the above steps, but I fixed it by restarting my Windows computer. Perhaps adding that would bring 80% up to 90%.

**Comment by auchenberg** [comment]
@bonniemurray Very interesting! Added to our FAQ. Glad you got doing!

**Comment by bsana1** [comment]
Hey all, thanks for getting back. 
So it turns out all I gotta do was to open safari on the device - until you do it, inspect doesn't show you anything so I thought it  was broken. Oh well, it works now, thanks!
