### ISSUE TITLE
DevTools: Overrides not working

### ISSUE THREAD

**Issue by zxerqw** [inspectdev/inspect-issues#96]
Can't use Overrides, after I select the folder, there is an authorization button at the top in chrome, which can't be displayed here
![image](https://user-images.githubusercontent.com/16666177/137052275-01033d8c-51f9-4ec7-88a4-bba434d449eb.png)

**Comment by zxerqw** [comment]
To be precise, the folders are not even selectable.

**Comment by zxerqw** [comment]
> To be precise, the folders are not even selectable.
I mean this button is invalid
![image](https://user-images.githubusercontent.com/16666177/137058014-b9416d61-166e-40c6-a399-1c911b690ff3.png)

**Comment by auchenberg** [comment]
Overrides are not supported with Webkit. We will disable this functionality in the front-end.
