### ISSUE TITLE
Highliht element not sync correctly

### ISSUE THREAD

**Issue by yvcabana** [inspectdev/inspect-issues#98]
- Inspect version: 0.7.4
- Electron: 13.1.1
- OS version and architecture: win32 x64 10.0.19043
- Language: undefined

Steps to Reproduce:

1.  In preview pane, scroll down
2. Html viewer are not sync with scrollbar, so we must scroll down manully

**Comment by auchenberg** [comment]
@yvcabana Is this the screencasting you are referring to?

**Comment by auchenberg** [comment]
Closing due to lack of validation
